### ISSUE TITLE
gitalk初始化问题

### ISSUE THREAD

**Issue by bupleurum** [bupleurum/comments#2]
@booxood 
您好，在使用gitalk过程中遇到如下问题：
我的Github Pages是hexo，主题是clean blog，我在clean blog的comments.ejs里增加了以下代码：
```
    <div id="gitalk-container"></div>
    </div>
    <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
    <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
    <script type="text/javascript">
        var gitalk = new Gitalk({
            clientID: 'b816e0222818d54c5eef',
            clientSecret: '6b28fac33f6aa27203f68a5b9a4afbdb050c2515',
            repo: 'comments',
            owner: 'bupleurum',
            admin: ['bupleurum'],
            distractionFreeMode: true
        })
        gitalk.render('gitalk-container');
    </script>
```
我的OAuth Application设置的Homepage URL是http://www.bupleurum.cn ，Authorization callback URL
是http://www.bupleurum.cn 。

在文章内提示
```
未找到相关的 Issues 进行评论

请联系 @bupleurum 初始化创建
```
并且我点击Issues能正确跳转到我设置的repo。
但是当我点击“使用Github登陆”，然后完成登陆后，有自动跳转到我的Github Pages首页，地址栏提示如下`http://www.bupleurum.cn/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch`，进入文章内，与之前现象一致，无法完成初始化。
我的Github Pages链接是www.bupleurum.cn有哪些地方我设置有误吗？请您指教，谢谢。

**Comment by booxood** [comment]
> Authorization callback URL 是 `http://www.bupleurum.cn`

修改为 `http://www.bupleurum.cn/` 试下看行不行

**Comment by bupleurum** [comment]
@booxood 
谢谢您的回复。
我目前设置的Authorization callback URL 就是http://www.bupleurum.cn

**Comment by booxood** [comment]
@bupleurum  是因为那篇文章的 `url` 上有空格导致的

**Comment by bupleurum** [comment]
@booxood 
确认了一下我的OAuth Application设置里url都是没有空格的。
是指Github Pages里的《Hellow World》里的url有空格？我看那篇文章里只有Gitalk加了个url，而且markdown写的时候也没空格呀，有点懵，我该怎么修改呢？

**Comment by booxood** [comment]
@bupleurum 你的配置没问题，是这篇文字的链接 `http://www.bupleurum.cn/2017/05/23/Hello%20World/` 里 `Hello World` 中间有个空格，指的是这个地方的空格

**Comment by booxood** [comment]
当进行 Github 认证跳转时，也就是点击 `使用 Github 登录` 时，会把当前链接(location.href)作为查询参数 redirect_uri 的值传递过去，这个值会跟你配置的 `Authorization callback URL` 进行验证，规则可以参考[这里](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps/#redirect-urls) ，如果 URL 上有空格，不管做不做 encodeURIComponent，都会校验失败，报
 `error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application`， Github 的文档上没有说明。

建议把 URL 上的空格替换成 `-`。

**Comment by booxood** [comment]
@bupleurum 不客气~
